source 'https://github.com/CocoaPods/Specs.git'
#source 'https://git2.baijiashilian.com/open-ios/specs.git'
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#  
#  pod 'Alamofire', '~> 5.9.0'
#  pod "BJVideoPlayerUI", :path => '/Users/fanyi/Documents/develop/develop/BJVideoPlayerUI'
#  pod "BJPlaybackUI", :path => '/Users/fanyi/Documents/develop/develop/BJPlaybackUI'
#  pod "BJPlayerUIBase", :path => '/Users/fanyi/Documents/develop/develop/BJPlayerUIBase'
#  pod 'BJVideoPlayerCore',                :path => '/Users/fanyi/Documents/develop/develop/BJVideoPlayerCore'
#  pod 'BJLiveBase',                       :path => '/Users/fanyi/Documents/develop/develop/BJLiveBase'
#  pod 'BJSwiftBase',                       :path => '/Users/fanyi/Documents/develop/develop/BJLiveBase'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end
